alpha: 0.8

bias_threshold: 0.85
bias_lambda: 0.6

components:
  A: 0.40   # conflict/war/violence (−)
  B: 0.25   # cooperation/aid/peace (+)
  C: 0.15   # disasters/crises (−)
  D: 0.10   # civics/rights/rule-of-law (+)
  E: 0.10   # science/medicine/innovation (+)

cluster:
  cosine_threshold: 0.28
  max_clusters_per_day: 150

history:
  min_days_for_stats: 14
  rolling_days: 0
