name: Compute Humanity Index

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run pipeline
        run: python -m pipeline.pipeline --days 1 --maxrecords 30 --output-dir public/data

      - run: mkdir -p public

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
