name: Compute Humanity Index

on:
  schedule:
    - cron: '5 1 * * *'   # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - name: Build site + data into ./public
        run: |
          set -eux
          rm -rf public
          mkdir -p public/data
          # Build data directly into the published folder
          python -m pipeline.pipeline --days 1 --maxrecords 30 --output-dir public/data
          # Copy the web files
          cp -r web/* public/
          # quick sanity check
          ls -R public

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
